### ISSUE TITLE
Support for Secrets in GitHub Environments

### ISSUE THREAD

**Issue by TrashManTrashCans** [kneemaa/github-action-rotate-aws-secrets#7]
When trying to rotate credentials stored in the new GitHub Environments, the action can read the secrets out of the Environment and do the necessary actions on the AWS side but when writing values it writes into the Repository secrets.

**Comment by kneemaa** [comment]
@TrashManTrashCans have you double checked that the User with the PAT token has Admin permissions to the repository it wants to update?

**Comment by TrashManTrashCans** [comment]
@kneemaa Yes, the PAT token has admin permissions. I think the issue is that the code here is hard coded to write to the root of the GitHub secrets for the repo, like [line 134 here](https://github.com/kneemaa/github-action-rotate-aws-secrets/blob/8eaa9fb17682a45d6481095c706ab777f39e2379/rotate_keys.py#L137). The secrets [Environment feature](https://docs.github.com/en/actions/reference/environments) sort of acts as a DIR within the root secrets repo and I think would require some sort of logic for the rotation action to work with it.
